services:
  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    command: uvicorn src.main:fastapi --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - './services/backend:/usr/src'
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.2
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7.0-bookworm
    command: ["redis-server", "--save \"\"", "--loglevel warning"]
    # volumes:
    #   - redis:/data
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379
    expose:
      - 6379